package com.capricorn.entity;

import java.util.Random;
/**
 * Define the cell with two attributes with letters and point.
 * Each cell should consisted with letters and potentially score('point').
 * The only method get is necesaary, and ignore the set method which is generated by random algrithm.
 */
public class Cell {
public String letter;
public String points;
//two attributes of cell letter and points
public String getLetter() {
	return letter;
}
public String getPoints() {
	return points;
}
//get method
/**Setletter replace the set method. The Letter should be define among english letter with unique posibility. */
public void setLetter() {
	String[] c = {"A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","R","S","T","U","V","W","X","Y","Z","Qu"};  
    //ebglish words domenstrated in order to be generated to the setletter function
	int k=0;
    int m=0;
    /**Here is the possiblity each word will appear in the game according to a big data analyze.
     * 810 means the value 8.1% and sum the value up is 10000.
     */
	int[] pro={810,149,278,425,1270,223,202,609,697,15,77,403,241,675,751,193,599,633,906,276,98,236,15,197,7,10};
    for(int i=0;i<=25;i++){
    	m+=pro[i];
    	}
    
    int[] w= new int[m];//repalce the word into whole number from 0 to 25.
    for(int i=0; i<=25;i++){
    	for(int j=1; j<=pro[i];j++){
    		w[k]=i;
    		k++;
    	}
    };
    /**Here is the points for each word correspond to the order from A to Z and Qu.*/
	String[] p = {"2","4","3","3","1","4","4","2","2","7","5","3","3","2","2","4","2","2","1","3","5","3","7","4","8","11"};
	Random random = new Random();  
//    for( int i = 0; i < 8; i ++) {  
//        System.out.println(c[random.nextInt(c.length)]); 
	int rand = random.nextInt(w.length);
	int q = w[rand];//write back to the matrix and convert the number into word 
    this.letter = c[q];
    this.points = p[q];
    
	}  

}


